/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.unesco.jisis.wizards.marc;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import org.openide.util.NbBundle;
import org.unesco.jisis.corelib.common.Global;
import org.unesco.jisis.jisisutils.FileExtFilter;


public final class ImportVisualPanel3 extends JPanel {

    /** Creates new form ImportVisualPanel3 */
    public ImportVisualPanel3() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #3";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSeparator3 = new javax.swing.JSeparator();
      jSeparator1 = new javax.swing.JSeparator();
      lblDBName = new javax.swing.JLabel();
      txtDBName = new javax.swing.JTextField();
      lblDBHome = new javax.swing.JLabel();
      cmbDBHome = new javax.swing.JComboBox();
      lblSubfieldSeparator = new javax.swing.JLabel();
      lblFirstMfn = new javax.swing.JLabel();
      lblTagWithMfn = new javax.swing.JLabel();
      lblReFmtFst = new javax.swing.JLabel();
      lblInputLineLength = new javax.swing.JLabel();
      txtReFmtFst = new javax.swing.JTextField();
      txtInputLineLength = new javax.swing.JTextField();
      txtSubfieldCharacter = new javax.swing.JTextField();
      txtFirstMfn = new javax.swing.JTextField();
      txtTagWithMfn = new javax.swing.JTextField();
      btnBrowseReFmtFst = new javax.swing.JButton();
      jSeparator2 = new javax.swing.JSeparator();
      jLabel1 = new javax.swing.JLabel();
      lblData = new javax.swing.JLabel();
      impFileName = new javax.swing.JTextField();
      btnIsoBrowse = new javax.swing.JButton();
      comboEncoding = new javax.swing.JComboBox();
      lblOption = new javax.swing.JLabel();
      rbtnMerge = new javax.swing.JRadioButton();
      rbtnLoad = new javax.swing.JRadioButton();
      rbtnUpdate = new javax.swing.JRadioButton();
      lblFST = new javax.swing.JLabel();
      lblFDT = new javax.swing.JLabel();
      impFST = new javax.swing.JTextField();
      impFDT = new javax.swing.JTextField();
      btnFDTBrowse = new javax.swing.JButton();
      btnFSTBrowse = new javax.swing.JButton();

      org.openide.awt.Mnemonics.setLocalizedText(lblDBName, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblDBName.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(lblDBHome, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblDBHome.text")); // NOI18N

      cmbDBHome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dummy" }));

      org.openide.awt.Mnemonics.setLocalizedText(lblSubfieldSeparator, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblSubfieldSeparator.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(lblFirstMfn, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblFirstMfn.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(lblTagWithMfn, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblTagWithMfn.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(lblReFmtFst, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblReFmtFst.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(lblInputLineLength, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblInputLineLength.text")); // NOI18N

      txtInputLineLength.setText(org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.txtInputLineLength.text")); // NOI18N

      txtSubfieldCharacter.setText(org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.txtSubfieldCharacter.text")); // NOI18N

      txtFirstMfn.setText(org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.txtFirstMfn.text")); // NOI18N

      txtTagWithMfn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtTagWithMfnActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(btnBrowseReFmtFst, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.btnBrowseReFmtFst.text")); // NOI18N

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
      org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.jLabel1.text")); // NOI18N

      lblData.setFont(new java.awt.Font("Tahoma", 1, 11));
      org.openide.awt.Mnemonics.setLocalizedText(lblData, NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblData.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(btnIsoBrowse, NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.btnIsoBrowse.text")); // NOI18N
      btnIsoBrowse.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnIsoBrowseActionPerformed(evt);
         }
      });

      comboEncoding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "US-ASCII", "CP850 (or IBM850)", "ISO-8859-1", "UTF-8", "UTF-16", "UTF-16BE", "UTF-16LE", " " }));
      comboEncoding.setSelectedIndex(1);
      comboEncoding.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboEncodingActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(lblOption, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblOption.text")); // NOI18N

      rbtnMerge.setSelected(true);
      org.openide.awt.Mnemonics.setLocalizedText(rbtnMerge, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.rbtnMerge.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(rbtnLoad, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.rbtnLoad.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(rbtnUpdate, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.rbtnUpdate.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(lblFST, NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblFST.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(lblFDT, NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.lblFDT.text")); // NOI18N

      org.openide.awt.Mnemonics.setLocalizedText(btnFDTBrowse, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.btnFDTBrowse.text")); // NOI18N
      btnFDTBrowse.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnFDTBrowseActionPerformed(evt);
         }
      });

      org.openide.awt.Mnemonics.setLocalizedText(btnFSTBrowse, org.openide.util.NbBundle.getMessage(ImportVisualPanel3.class, "ImportVisualPanel3.btnFSTBrowse.text")); // NOI18N
      btnFSTBrowse.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnFSTBrowseActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 609, Short.MAX_VALUE)
         .addGap(0, 609, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                  .addContainerGap())
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                  .addContainerGap())
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDBName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDBName))
                     .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDBHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDBHome, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(380, 380, 380))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(lblSubfieldSeparator)
                     .addComponent(lblFirstMfn)
                     .addComponent(lblTagWithMfn)
                     .addComponent(lblReFmtFst)
                     .addComponent(lblInputLineLength))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtReFmtFst, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                     .addComponent(txtInputLineLength, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                           .addComponent(txtSubfieldCharacter, javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtFirstMfn, javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(txtTagWithMfn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(178, 178, 178)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnBrowseReFmtFst)
                  .addGap(71, 71, 71))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel1)
                           .addComponent(lblData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(impFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btnIsoBrowse))
                           .addComponent(comboEncoding, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                  .addContainerGap())
               .addGroup(layout.createSequentialGroup()
                  .addComponent(lblOption)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(rbtnMerge)
                  .addGap(6, 6, 6)
                  .addComponent(rbtnLoad)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(rbtnUpdate)
                  .addContainerGap(392, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(lblFST)
                     .addComponent(lblFDT))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(impFST, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                     .addComponent(impFDT, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(btnFDTBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnFSTBrowse))
                  .addContainerGap())))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 447, Short.MAX_VALUE)
         .addGap(0, 447, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblDBHome)
               .addComponent(cmbDBHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblDBName)
               .addComponent(txtDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(5, 5, 5)
                  .addComponent(lblFDT))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(impFDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnFDTBrowse))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(impFST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnFSTBrowse)
                     .addComponent(lblFST))))
            .addGap(14, 14, 14)
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnIsoBrowse)
               .addComponent(impFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(lblData))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(comboEncoding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(rbtnMerge)
               .addComponent(rbtnLoad)
               .addComponent(rbtnUpdate)
               .addComponent(lblOption))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblSubfieldSeparator)
               .addComponent(txtSubfieldCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblFirstMfn)
               .addComponent(txtFirstMfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblTagWithMfn)
               .addComponent(txtTagWithMfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblReFmtFst)
               .addComponent(txtReFmtFst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnBrowseReFmtFst))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblInputLineLength)
               .addComponent(txtInputLineLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void txtTagWithMfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagWithMfnActionPerformed
      // TODO add your handling code here:
}//GEN-LAST:event_txtTagWithMfnActionPerformed

   private void btnIsoBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsoBrowseActionPerformed
      impFileName.setText(selectFile("iso", "ISIS ISO exported files"));
}//GEN-LAST:event_btnIsoBrowseActionPerformed

   private void comboEncodingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEncodingActionPerformed
      // TODO add your handling code here:
}//GEN-LAST:event_comboEncodingActionPerformed

   private void btnFDTBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFDTBrowseActionPerformed
      impFDT.setText(selectFile("fdt", "ISIS FDT Files"));
}//GEN-LAST:event_btnFDTBrowseActionPerformed

   private void btnFSTBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFSTBrowseActionPerformed
      impFST.setText(selectFile("fst", "ISIS FST Files"));
}//GEN-LAST:event_btnFSTBrowseActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnBrowseReFmtFst;
   private javax.swing.JButton btnFDTBrowse;
   private javax.swing.JButton btnFSTBrowse;
   private javax.swing.JButton btnIsoBrowse;
   private javax.swing.JComboBox cmbDBHome;
   private javax.swing.JComboBox comboEncoding;
   private javax.swing.JTextField impFDT;
   private javax.swing.JTextField impFST;
   private javax.swing.JTextField impFileName;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JLabel lblDBHome;
   private javax.swing.JLabel lblDBName;
   private javax.swing.JLabel lblData;
   private javax.swing.JLabel lblFDT;
   private javax.swing.JLabel lblFST;
   private javax.swing.JLabel lblFirstMfn;
   private javax.swing.JLabel lblInputLineLength;
   private javax.swing.JLabel lblOption;
   private javax.swing.JLabel lblReFmtFst;
   private javax.swing.JLabel lblSubfieldSeparator;
   private javax.swing.JLabel lblTagWithMfn;
   private javax.swing.JRadioButton rbtnLoad;
   private javax.swing.JRadioButton rbtnMerge;
   private javax.swing.JRadioButton rbtnUpdate;
   private javax.swing.JTextField txtDBName;
   private javax.swing.JTextField txtFirstMfn;
   private javax.swing.JTextField txtInputLineLength;
   private javax.swing.JTextField txtReFmtFst;
   private javax.swing.JTextField txtSubfieldCharacter;
   private javax.swing.JTextField txtTagWithMfn;
   // End of variables declaration//GEN-END:variables
private String selectFile(String ext, String description) {

       //prefs = Preferences.userNodeForPackage(this.getClass());
       String lastDir = Global.prefs_.get("IMPEXP_INPUT_DIR", "");
       JFileChooser fc = new JFileChooser(lastDir);

       // Remove the filter that accepts all files
       FileFilter ft = fc.getAcceptAllFileFilter();
       fc.removeChoosableFileFilter(ft);

       // Add the file extension filter
       FileExtFilter filter = new FileExtFilter(ext,description);
       fc.addChoosableFileFilter(filter);

        fc.showOpenDialog(this);
        File file;
        if ((file=fc.getSelectedFile())!= null) {
           Global.prefs_.put("IMPEXP_INPUT_DIR", file.getAbsolutePath());
            return file.getAbsolutePath();
        }
        return "";
    }
}

