/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RtlSelectDlg.java
 *
 * Created on Mar 18, 2009, 3:19:23 PM
 */

package org.unesco.jisis.databrowser;

/**
 *
 * @author jc_dauphin
 */
public class RtlSelectDlg extends javax.swing.JDialog {

    protected String encoding_ = null;
    protected boolean succeeded_ = false;
    protected String[] columnNames_;
    /** Creates new form RtlSelectDlg */
    public RtlSelectDlg(String[] names, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        columnNames_ = names;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      lstSelectColumn = new org.unesco.jisis.jisisutils.gui.CheckBoxList(columnNames_);
      btnOK = new javax.swing.JButton();
      btnCancel = new javax.swing.JButton();
      btbCheckAll = new javax.swing.JButton();
      btnUncheckAll = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jScrollPane1.setViewportView(lstSelectColumn);

      btnOK.setText(org.openide.util.NbBundle.getMessage(RtlSelectDlg.class, "RtlSelectDlg.btnOK.text")); // NOI18N
      btnOK.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOKActionPerformed(evt);
         }
      });

      btnCancel.setText(org.openide.util.NbBundle.getMessage(RtlSelectDlg.class, "RtlSelectDlg.btnCancel.text")); // NOI18N
      btnCancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelActionPerformed(evt);
         }
      });

      btbCheckAll.setText(org.openide.util.NbBundle.getMessage(RtlSelectDlg.class, "RtlSelectDlg.btbCheckAll.text")); // NOI18N
      btbCheckAll.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btbCheckAllActionPerformed(evt);
         }
      });

      btnUncheckAll.setText(org.openide.util.NbBundle.getMessage(RtlSelectDlg.class, "RtlSelectDlg.btnUncheckAll.text")); // NOI18N
      btnUncheckAll.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUncheckAllActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(21, 21, 21)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(31, 31, 31)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(btbCheckAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(btnUncheckAll, javax.swing.GroupLayout.Alignment.LEADING)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addContainerGap(359, Short.MAX_VALUE)
                  .addComponent(btnOK)
                  .addGap(29, 29, 29)
                  .addComponent(btnCancel)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(113, 113, 113)
            .addComponent(btbCheckAll)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnUncheckAll)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnOK)
               .addComponent(btnCancel))
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addGap(111, 111, 111))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void btbCheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCheckAllActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_btbCheckAllActionPerformed

    private void btnUncheckAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUncheckAllActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_btnUncheckAllActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        succeeded_ = false;
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        succeeded_ = true;
       dispose();
    }//GEN-LAST:event_btnOKActionPerformed
  public boolean succeeded() {
      return succeeded_;
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RtlSelectDlg dialog = new RtlSelectDlg( new String[] {"item1","item2"},new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btbCheckAll;
   private javax.swing.JButton btnCancel;
   private javax.swing.JButton btnOK;
   private javax.swing.JButton btnUncheckAll;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JList lstSelectColumn;
   // End of variables declaration//GEN-END:variables

}
