/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SuggestionsOptionlDialog.java
 *
 * Created on 29 janv. 2010, 15:47:23
 */

package org.unesco.jisis.datasearch;

/**
 *
 * @author jcd
 */
public class SuggestionsOptionDialog extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
     public static final int SORT_FIELD_TERM_FREQ = 0;
     public static final int SORT_TERM_FIELD_FREQ = 1;
     public static final int TERM_CASE_SENSITIVE  = 2;
     public static final int TERM_CASE_INSENSITIVE = 3;

    protected int termSorting_ = SORT_TERM_FIELD_FREQ;


    protected int termCaseSensitivity_ = TERM_CASE_INSENSITIVE;
    protected boolean succeeded_ = false;

    /** Creates new form SuggestionsOptionlDialog */
    public SuggestionsOptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setOptions(int termSorting, int termCaseSensitivity) {
       termSorting_ = termSorting;
       if (termSorting == this.SORT_TERM_FIELD_FREQ) {
          rdbSortTermFieldFreq.setSelected(true);
          rdbSortFieldTermFreq.setSelected(false);
       } else {
           rdbSortTermFieldFreq.setSelected(false);
          rdbSortFieldTermFreq.setSelected(true);
       }
       termCaseSensitivity_ = termCaseSensitivity;
       if (termCaseSensitivity == this.TERM_CASE_SENSITIVE) {
          rdbCaseSensitive.setSelected(true);
          rdbCaseInsensitive.setSelected(false);
       } else {
          rdbCaseSensitive.setSelected(false);
          rdbCaseInsensitive.setSelected(true);
       }
    }
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup1 = new javax.swing.ButtonGroup();
      buttonGroup2 = new javax.swing.ButtonGroup();
      okButton = new javax.swing.JButton();
      cancelButton = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      rdbSortTermFieldFreq = new javax.swing.JRadioButton();
      rdbSortFieldTermFreq = new javax.swing.JRadioButton();
      jLabel2 = new javax.swing.JLabel();
      rdbCaseInsensitive = new javax.swing.JRadioButton();
      rdbCaseSensitive = new javax.swing.JRadioButton();

      setTitle(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.title")); // NOI18N
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosing(java.awt.event.WindowEvent evt) {
            closeDialog(evt);
         }
      });

      okButton.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.okButton.text")); // NOI18N
      okButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            okButtonActionPerformed(evt);
         }
      });

      cancelButton.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.cancelButton.text")); // NOI18N
      cancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelButtonActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
      jLabel1.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.jLabel1.text")); // NOI18N

      buttonGroup1.add(rdbSortTermFieldFreq);
      rdbSortTermFieldFreq.setSelected(true);
      rdbSortTermFieldFreq.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.rdbSortTermFieldFreq.text")); // NOI18N
      rdbSortTermFieldFreq.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rdbSortTermFieldFreqActionPerformed(evt);
         }
      });

      buttonGroup1.add(rdbSortFieldTermFreq);
      rdbSortFieldTermFreq.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.rdbSortFieldTermFreq.text")); // NOI18N
      rdbSortFieldTermFreq.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rdbSortFieldTermFreqActionPerformed(evt);
         }
      });

      jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
      jLabel2.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.jLabel2.text")); // NOI18N

      buttonGroup2.add(rdbCaseInsensitive);
      rdbCaseInsensitive.setSelected(true);
      rdbCaseInsensitive.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.rdbCaseInsensitive.text")); // NOI18N
      rdbCaseInsensitive.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rdbCaseInsensitiveActionPerformed(evt);
         }
      });

      buttonGroup2.add(rdbCaseSensitive);
      rdbCaseSensitive.setText(org.openide.util.NbBundle.getMessage(SuggestionsOptionDialog.class, "SuggestionsOptionDialog.rdbCaseSensitive.text")); // NOI18N
      rdbCaseSensitive.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            rdbCaseSensitiveActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(337, Short.MAX_VALUE)
            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cancelButton)
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(82, 82, 82)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(rdbCaseSensitive)
                  .addComponent(rdbCaseInsensitive)
                  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(rdbSortFieldTermFreq, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                  .addComponent(rdbSortTermFieldFreq)))
            .addContainerGap(130, Short.MAX_VALUE))
      );

      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(31, 31, 31)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rdbSortTermFieldFreq)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rdbSortFieldTermFreq)
            .addGap(29, 29, 29)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rdbCaseInsensitive)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rdbCaseSensitive)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(cancelButton)
               .addComponent(okButton))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       succeeded_ = true;
       doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
         succeeded_ = false;
         doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void rdbSortFieldTermFreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSortFieldTermFreqActionPerformed
       termSorting_= SuggestionsOptionDialog.SORT_FIELD_TERM_FREQ;
    }//GEN-LAST:event_rdbSortFieldTermFreqActionPerformed

    private void rdbSortTermFieldFreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbSortTermFieldFreqActionPerformed
       termSorting_= SuggestionsOptionDialog.SORT_TERM_FIELD_FREQ;
    }//GEN-LAST:event_rdbSortTermFieldFreqActionPerformed

    private void rdbCaseInsensitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCaseInsensitiveActionPerformed
        termCaseSensitivity_ = SuggestionsOptionDialog.TERM_CASE_INSENSITIVE;
    }//GEN-LAST:event_rdbCaseInsensitiveActionPerformed

    private void rdbCaseSensitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCaseSensitiveActionPerformed
       termCaseSensitivity_ = SuggestionsOptionDialog.TERM_CASE_SENSITIVE;
    }//GEN-LAST:event_rdbCaseSensitiveActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
   public boolean succeeded() {
      return succeeded_;
   }

   public int getTermCaseSensitivity() {
      return termCaseSensitivity_;
   }


   public int getTermSorting() {
      return termSorting_;
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuggestionsOptionDialog dialog = new SuggestionsOptionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.ButtonGroup buttonGroup2;
   private javax.swing.JButton cancelButton;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JButton okButton;
   private javax.swing.JRadioButton rdbCaseInsensitive;
   private javax.swing.JRadioButton rdbCaseSensitive;
   private javax.swing.JRadioButton rdbSortFieldTermFreq;
   private javax.swing.JRadioButton rdbSortTermFieldFreq;
   // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
